tap 'caskroom/cask'

brew 'mas'
brew 'qlcolorcode'
brew 'qlstephen'
brew 'qlmarkdown'
brew 'quicklook-json'
brew 'qlprettypatch'
brew 'quicklook-csv'
brew 'betterzipql'
brew 'webpquicklook'
brew 'zsh'
brew 'zsh-completions'
brew 'tree'
brew 'fzf'
brew 'ack'
brew 'git'
brew 'vim'
brew 'pyenv'
brew 'mysql'
brew 'rbenv'
brew 'ruby-build'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'node'
brew 'golang'
brew 'heroku-toolbelt'
brew 'youtube-dl'
brew 'ffmpeg'
brew 'ghostscript'
brew 'github-markdown-toc'

cask 'alfred'
cask 'android-platform-tools'
cask 'appcleaner'
cask 'google-backup-and-sync'
cask 'bettertouchtool'
cask 'docker'
cask 'filezilla'
cask 'flux'
cask 'github-desktop'
cask 'google-chrome'
cask 'iterm2'
cask 'lastpass'
cask 'macdown'
cask 'microsoft-office'
cask 'recordit'
cask 'sequel-pro'
cask 'skim'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'sublime-text'
cask 'transmission'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'vlc'

mas 'Amphetamine', id: 937984704
mas 'LastPass: Password Manager and Secure Vault', id: 926036361
mas 'The Unarchiver', id: 425424353
