tap 'caskroom/cask'

brew 'ffmpeg'
brew 'ghostscript'
brew 'git'
brew 'github-markdown-toc'
brew 'mas'
brew 'mysql'
brew 'node'
brew 'python'
brew 'python@2'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'anaconda'
cask 'appcleaner'
cask 'authy'
cask 'blockblock'
cask 'google-backup-and-sync'
cask 'bettertouchtool'
cask 'evernote'
cask 'filezilla'
cask 'github-desktop'
cask 'google-chrome'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'knockknock'
cask 'malwarebytes'
cask 'oversight'
cask 'recordit'
cask 'sequel-pro'
cask 'skype'
cask 'spectacle'
cask 'spotify'
cask 'steam'
cask 'sublime-text'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'

mas 'Amphetamine', id: 937984704
mas 'LastPass: Password Manager and Secure Vault', id: 926036361
mas 'The Unarchiver', id: 425424353
